### ISSUE TITLE
problem of the attention

### ISSUE THREAD

**Issue by liuxingbin** [essunny310/FreestyleNet#10]
Hi, FreestyleNet is a great work. However, I am confused about the attention mechanism. During inference, we use attention_FLIS.py, which involves words with more than one token. Then why we should specifically design the attention for COCO and ADE20k?

I am looking forward to your reply.

**Comment by essunny310** [comment]
Hi there, great question! You can indeed use attention_FLIS.py for COCO and ADE20K during inference as [these lines of code](https://github.com/essunny310/FreestyleNet/blob/5dcb8b84e150509456eaa5aeec09b505c7a6766f/scripts/FLIS.py#L44C1-L46C59) would help us to handle words with more than one token. We opted to apply attention_ADE20K.py and attention_COCO.py, in the sense that this kind of "hard“ coding will save time especially during training.

Feel free to ask if you have any remaining questions.

**Comment by liuxingbin** [comment]
That's helped me a lot. Thanks for your reply.
