### ISSUE TITLE
The  semantic masks generation.

### ISSUE THREAD

**Issue by 6Roy** [essunny310/FreestyleNet#12]
Hello, Great Work. Could you tell me how to get the semantic masks in the paper? Did you draw them by yourself?

**Comment by essunny310** [comment]
Hi, thanks for your attention.

The semantic masks in this paper are all from ADE20K/COCO-Stuff. You can draw one by yourself and perform FLIS following [this](https://github.com/essunny310/FreestyleNet?tab=readme-ov-file#freestyle-layout-to-image-synthesis-flis).
