### ISSUE TITLE
model prolem of "openai/clip-vit-large-patch14"

### ISSUE THREAD

**Issue by Amazingren** [essunny310/FreestyleNet#5]
Dear @essunny310,

It's really nice to see your impressive work. However, during I tried to train the FreestyleNet, it shows me the following errors,
<img width="887" alt="image" src="https://github.com/essunny310/FreestyleNet/assets/31409716/696f3ec3-b15a-42db-96a5-d27f300d8dc1">

 
Could you show me some possible solutions when you are free?

Bests,

**Comment by Amazingren** [comment]
solved

**Comment by beeternity** [comment]
Hello, I have the same problem, could you please share  your solution when you are free? Thanks!

**Comment by FeboReigns** [comment]
Hello, I have the same problem, could you please share your solution when you are free? Thanks!

**Comment by Amazingren** [comment]
您的来信已经收到，稍后进行回复，谢谢~
