### ISSUE TITLE
how to use input as bounding box not segmentation mask work for this application?

### ISSUE THREAD

**Issue by shileims** [essunny310/FreestyleNet#6]
Hi author, 
Thanks for your excellent work.
how to use input as bounding box not segmentation mask work for this application?

**Comment by essunny310** [comment]
Thanks for your interest.

Our model is designed to generate objects whose shape conforms to the corresponding mask. Moreover, the masks of all objects do not overlap. I would recommend using other methods that generate images from bounding boxes such as https://github.com/silent-chen/layout-guidance, https://github.com/ZGCTroy/LayoutDiffusion and https://github.com/cplusx/layout_diffuse.
