### ISSUE TITLE
How to change the output image resolution?

### ISSUE THREAD

**Issue by Fengzexu** [essunny310/FreestyleNet#7]
Hello, very inspiring work! How to output an image with the same resolution size as the input image? Do I need to retrain？I just came into contact with this field, please forgive me if there is something wrong.

**Comment by essunny310** [comment]
Thanks for your interest in FreestyleNet. You can resize the output image [here](https://github.com/essunny310/FreestyleNet/blob/5dcb8b84e150509456eaa5aeec09b505c7a6766f/scripts/FLIS.py#L226).

**Comment by Fengzexu** [comment]
Thank you for your reply！ Using resize will cause a decrease in the quality of generated images. Can we modify it from the model network level? But I noticed that stable diffusion can only generate images of 512/768 size. Do you have any good ideas about this issue? Thank you！

**Comment by essunny310** [comment]
You can also try this:
1. Replace [this line](https://github.com/essunny310/FreestyleNet/blob/5dcb8b84e150509456eaa5aeec09b505c7a6766f/scripts/FLIS.py#L33) with
```python
w, h = map(lambda x: x - x % 64, (label.size[0], label.size[1]))
label = label.resize((w, h), resample=Image.NEAREST)
```
2. After [this line](https://github.com/essunny310/FreestyleNet/blob/5dcb8b84e150509456eaa5aeec09b505c7a6766f/scripts/FLIS.py#L188), insert the following code
```python
opt.H = label.shape[1]
opt.W = label.shape[2]
```
3. Replace [this line](https://github.com/essunny310/FreestyleNet/blob/5dcb8b84e150509456eaa5aeec09b505c7a6766f/ldm/modules/attention_FLIS.py#L191) and [this line](https://github.com/essunny310/FreestyleNet/blob/5dcb8b84e150509456eaa5aeec09b505c7a6766f/ldm/modules/attention_FLIS.py#L192) with
```python
ratio = label.shape[1] / label.shape[2]
H = int(math.sqrt(q.shape[1] / ratio) * ratio)
W = int(math.sqrt(q.shape[1] / ratio))
```

For the LIS setting, you could modify `scripts/LIS.py`, `ldm/modules/attention_ADE20K.py`, and `ldm/modules/attention_COCO.py` in a similar way.

**Comment by Fengzexu** [comment]
Thank you for your patience, this is very helpful for me！
