### ISSUE TITLE
Cityscapes results

### ISSUE THREAD

**Issue by DZhaoXd** [essunny310/FreestyleNet#8]
Very inspiring work!
I saw the generation results about Cityscapes.  If it is convenient to provide the corresponding training scripts and trained weights? 
Thanks a lot.

**Comment by essunny310** [comment]
Thanks for your attention!
Similar to ADE20K and COCO-Stuff, training FreestyleNet on Cityscapes is simple. The following steps are for your reference:

1. Download the dataset and prepare `Cityscapes_train.txt` and `Cityscapes_val.txt` that contain the path to each image. Write a `Cityscapes.py` (please refer to [ADE20K.py](https://github.com/essunny310/FreestyleNet/blob/main/ldm/data/ADE20K.py)) and place it in `ldm/data/`.
2. Write a `attention_Cityscapes.py` (please refer to [attention_ADE20K.py](https://github.com/essunny310/FreestyleNet/blob/main/ldm/modules/attention_ADE20K.py)) and place it in `ldm/modules/`.
3. Write a `openaimodel_Cityscapes.py` (please refer to [openaimodel_ADE20K.py](https://github.com/essunny310/FreestyleNet/blob/main/ldm/modules/diffusionmodules/openaimodel_ADE20K.py)) and place it in `ldm/modules/diffusionmodules/`.
4. Write a `v1-finetune_Cityscapes.yaml` (please refer to [v1-finetune_ADE20K.yaml](https://github.com/essunny310/FreestyleNet/blob/main/configs/stable-diffusion/v1-finetune_ADE20K.yaml)) and place it in `configs/stable-diffusion/`.
5. Create a `train_Cityscapes.sh` (please refer to [train_ADE20K.sh](https://github.com/essunny310/FreestyleNet/blob/main/train_ADE20K.sh)) and you can now execute it to start training!

Feel free to ask if you have any further questions:)

**Comment by DZhaoXd** [comment]
Thx !
