### ISSUE TITLE
how  to get json file that defines the mapping between text and layout.

### ISSUE THREAD

**Issue by joanChen0212** [essunny310/FreestyleNet#9]
Excuse me , how  to get json file that defines the mapping between text and layout if I want to generate images in a freestyle way?What is the label value?

**Comment by essunny310** [comment]
The label value is associated with the pixel value of a region in the layout image. In short, you need to provide a description for each region in the layout, thus the mapping is defined as <"your description for a region": pixel value of that region in the layout>. Feel free to reach out if you have any further questions.

**Comment by joanChen0212** [comment]
Thanks for your reply ! Could you please tell me what tool you used to get the pixel values for each region in the layout?
Thank you a lot~

**Comment by essunny310** [comment]
It depends on how you get the layout images. Those provided in `./examples/` are from COCO-Stuff dataset, and you can refer to 
[this](https://github.com/essunny310/FreestyleNet/blob/5dcb8b84e150509456eaa5aeec09b505c7a6766f/ldm/data/COCO.py) to obtain the pixel values.

**Comment by joanChen0212** [comment]
Thanks for your reply ! your reply help me a lot!
